language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -e . --use-mirrors
script:
  - python setup.py test
after_success:
  - pip install -q --use-mirrors python-coveralls
  - coveralls
